BEGIN;
CREATE TABLE test_table(
    id INTEGER PRIMARY KEY,
    param_1 INTEGER NOT NULL,
    param_2 INTEGER NOT NULL,
    param_3 INTEGER NOT NULL,
    param_4 DOUBLE PRECISION NOT NULL,
    param_5 DOUBLE PRECISION NOT NULL,
    param_6 DOUBLE PRECISION NOT NULL
);
COMMIT;